version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: always
    volumes:
      - .:/app
    environment:
      - NGINX_HOST=localhost

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
      - "5001:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
